Language it
mihaituhari/rescue4x4-language pull request #2
Opened 2022-04-05 17:03 UTC by MirkoVentura

**What type of request did you want to push:**
- [x] Add new language
- [ ] Fix existing language
- [ ] Other

**Which is the new behavior:**
> Details about new language, changes or bugs fixed

2022-04-05 17:04 UTC, MirkoVentura commented
still draft but with the pr open I will remember to complete it 🚀

2022-04-05 17:16 UTC, mihaituhari requested changes

2022-04-05 17:16 UTC, mihaituhari commented on src/language_it.inc.php
> +$ARR_LANGUAGE_EN = [
```suggestion
$ARR_LANGUAGE_IT = [
```

2022-04-11 07:34 UTC, MirkoVentura commented
closing since duplicated of https://github.com/mihaituhari/rescue4x4-language/pull/3

2022-04-11 07:34 UTC, closed without merging